name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a multi Line
      run: git diff --name-only HEAD HEAD~1 > okay; while read l; do echo "#${l}#"; done < okay
